spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: root
    password: 123456
    url: jdbc:h2:mem:subs-control-test;MODE=POSTGRESQL;DATABASE_TO_LOWER=TRUE # É possível persistir em um arquivo alterando "mem:subs-control-test" para "file:./.h2/dev"
  h2:
    console:
      enabled: true
      path: /h2