CREATE TABLE SUB_PROVIDERS (
    ID VARCHAR(36) NOT NULL PRIMARY KEY,
    TYPE VARCHAR(36) NOT NULL CHECK (TYPE IN ('PATREON')),
    NAME VARCHAR(255) NOT NULL,
    BASE_URL VARCHAR(255) NOT NULL,
    CLIENT_ID VARCHAR(255),
    CLIENT_SECRET VARCHAR(255),
    AUTHORIZATION_URL VARCHAR(255),
    TOKEN_URL VARCHAR(255),
    ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    LAST_SYNC TIMESTAMP(6)
);

CREATE TABLE CONTENT_PROVIDERS (
    ID VARCHAR(36) NOT NULL PRIMARY KEY,
    TYPE VARCHAR(36) NOT NULL CHECK (TYPE IN ('GOOGLE_DRIVE')),
    NAME VARCHAR(255) NOT NULL,
    BASE_URL VARCHAR(255) NOT NULL,
    CLIENT_ID VARCHAR(255),
    CLIENT_SECRET VARCHAR(255),
    AUTHORIZATION_URL VARCHAR(255),
    TOKEN_URL VARCHAR(255),
    ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    LAST_SYNC TIMESTAMP(6)
);